[tool.pytest.ini_options]
pythonpath = ["trendify"]
addopts = "--junitxml=junittest.xml --cov-report xml --cov-report term:skip-covered --cov-branch"
testpaths = ["tests"]

[tool.mypy]
ignore_missing_imports = "True"

[tool.pylint.messages_control]
disable = ["C0114", "C0115", "C0116", "C0301", "R0903", "W0511", "W0621", "W0632", "W1203"]
good-names = ["df"]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
